### ISSUE TITLE
GraphQL Subscriptions Without Swole return Instantly.

### ISSUE THREAD

**Issue by agentd00nut** [leocavalcante/siler#281]
I'm trying to follow 

https://siler.leocavalcante.dev/graphql#graphql-subscriptions

My issue is when i issue a gQL query with `subscription` as the type it returns instantly instead of `The result will not be immediate since we are now listening to new messages, not querying them.

Boiled down i have two servers; one running with `php -S 127.0.0.1:8000 index.php` the other with just `php subscriptions.php`

The expected outcome is that when i query `http://127.0.01:8000/` with
```
subscription {
    subTest(secret: "aSecretKey")
}
```
that the query would hang / idle until i make another query to `http://api-local.rainway.com:8000/` with
```
mutation{
    pubTest(s: "mySecretIsSpooky", p:"hi there spooky!")
}
```

Instead what happens is the subscription query immediately responds with `this return quickly:` (see below)

Boiled down to the important parts (hopefully) my files look like.
index.php
```
use Siler\GraphQL;


if (Request\method_is('post')) {

    $schema = include __DIR__.'/schema.php';
    GraphQL\init($schema);
}
```

schema.php
```
include_once 'vendor/autoload.php';
use Siler\GraphQL;
$typeDefs = file_get_contents(__DIR__.'/schema.graphql');
$resolvers = include __DIR__ . '/src/resolvers/Resolvers.php';
return GraphQL\schema($typeDefs, $resolvers);
```

schema.gql
```
type Mutation{
	pubTest(s:String!, p:String!): Boolean!
}

type Subscription {
    subTest(s: String): String
}
```

Resolvers.php
```
GraphQL\subscriptions_at('ws://127.0.0.1:3000');

$queryType=array();
$mutationType=array();
$subscriptionType=array();


$subscriptionType['subTest'] = function($x){
    return "this return quickly: ".json_encode($x);
};

$mutationType['pubTest'] = function($root, $args){
    Siler\GraphQL\publish('subTest', ['s'=>$args['s'], 'p'=>$args['p']]);
    return true;
};

return [
    'Query'=>$queryType,
    'Mutation'=>$mutationType,
    'Subscription'=>$subscriptionType
];
```

And then the subscriptions.php...

```
use Siler\GraphQL;

require 'vendor/autoload.php';

$schema = include __DIR__.'/schema.php';

$x = GraphQL\subscriptions($schema, [], '127.0.0.1', 3000);
$x->run();
```

I notice the #226 and example graphQL use Swole with the SubscriptionManager... is this now required?

**Comment by leocavalcante** [comment]
Please, make sure you are using the lasted version of Siler, this initial data on subscriptions was fixed at https://github.com/leocavalcante/siler/pull/228

> I notice the #226 and example graphQL use Swole with the SubscriptionManager... is this now required?

Yes, calling `Siler\GraphQL\subscriptions` is now deprecated since there is a support for subscriptions based on Swoole too; now you have to pass a manager to Ratchet (or Swoole).

**Comment by agentd00nut** [comment]
Upgraded everything but was getting...

`[Tue Mar 17 09:38:03 2020] PHP Fatal error:  Uncaught Error: Class 'WebSocket\Client' not found in .../vendor/leocavalcante/siler/src/GraphQL/GraphQL.php:348`

Completely removed my `vendor` and `composer` files, re-required everything that i can find that siler says you need for graphQL
```{
    "require": {
        "leocavalcante/siler": "^1.7",
        "cboden/ratchet": "^0.4.2",
        "ratchet/pawl": "^0.3.4",
        "webonyx/graphql-php": "^0.13.8",
        "monolog/monolog": "^2.0",
    }
}```

Still the same error... had to manually require `textalk/websocket

Had to do `composer require "textalk/websocket"`  

Might want to update the requirements in the documentation to include the textalk/websocket requirement.

**Comment by agentd00nut** [comment]
Also now getting
```
PHP Fatal error:  Uncaught WebSocket\ConnectionException: Connection to 'ws://0.0.0.0/' failed: Server sent invalid upgrade response:
HTTP/1.1 426 No Sec-WebSocket-Protocols requested supported
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Protocol: graphql-ws
X-Powered-By: Ratchet/0.4.1
```

My index.php is basically the same. 

Subscriptions.php changed to
```
$manager = GraphQL\subscriptions_manager($schema);
Siler\Ratchet\graphql_subscriptions($manager,3000,'0.0.0.0')->run();
```

**Comment by agentd00nut** [comment]
Ping on this;  Doesn't seem right that even the swoole example (or very close to it) is having this issue.

(Sorry i realize you're the lone dev just not sure where to even look to try and alleviate the issue.)

**Comment by lemonbrain-mk** [comment]
Here some handy informations:
https://www.swoole.co.uk/article/Build-a-GraphQL-API-on-top-of-Swoole
https://www.swoole.co.uk/docs/get-started/installation

**Comment by leocavalcante** [comment]
@agentd00nut can you build a small project that reproduces the error? I'm not being able reproduce this to debug, also please share what client you are using to connect to the graphql api.

**Comment by lemonbrain-mk** [comment]
Ok i found the problem. The problem will be coming from my business domain i think, but i'm not sure. so i normally dont define different types in my resolver i just return a stdClass. but i tried to change this and did definition for every type and gave some doctrine entities back. and this was working perfectly with graphql but not with websockets. for some reason i don't get the same parameters in there i think. 
```
class PeopleResolver
{
    public static function get()
    {
        $person = [
            'id' => function ($person) {
                echo $person;
                return $person->get_id();
            },
            'commitments' => function ($person) { //Person sometimes is an entity and through websocket an array
                return $person->get_commitments() ? array_merge(array_filter($person->get_commitments()->toArray(), function ($item) {
                    if ($item->get_deleted_from() > 0) {
                        return false;
                    }
                    return true;
                }), []) : [];
            },
```

**Comment by lemonbrain-mk** [comment]
I know its here the wrong place, but how would you secure the websocket server, is there a jwt possability or does it not make sense?

**Comment by leocavalcante** [comment]
Sorry about that guys, websocket subprotocol isn't on any release yet, please use `dev-master`.
https://github.com/siler-examples/issue-281

```json
{
    "require": {
        "leocavalcante/siler": "dev-master"
    }
}
```

**Comment by agentd00nut** [comment]
Sorry for reopening this issue but still having trouble with this...

Using https://github.com/siler-examples/issue-281 ; making no changes to the code at all.

Still having the issue that `subscription` requests resolve immediately.

Running in two consoles (i've also tried port 8000 for the index)
`sudo php -S 0.0.0.0:80 -t .` and in another `php subscriptions.php`

When using [insomnia](https://insomnia.rest/) a subscription query of

```
subscription {hello}
``` 

Comes back immediately with 
```
{
  "data": {
    "hello": "hello world from subscription"
  }
}
```

What i would expect is that the connection would hold until a `query{hello}` request comes in and publishes against the `hello` subscription and then the subscription request would receive its data back.

I noticed the docs recommended using [graphQL Playground](https://github.com/prisma-labs/graphql-playground) so when using gql playground what's interesting is it works fine for the `query` request (same as insomnia); but fails to even connect to the server when doing a `subscription` request.

```
{
  "error": "Could not connect to websocket endpoint ws://localhost. Please check if the endpoint url is correct."
}
```

At least the way the playground is trying to connect makes a lot more sense to me, seeing that its a subscription and trying to use a websocket.

**Comment by leocavalcante** [comment]
I'll be checking this.

**Comment by leocavalcante** [comment]
How are you adding subscriptions to Insomnia? I think the gap is there: https://github.com/Kong/insomnia/issues/528
That is why it works on WebSocket enabled clients like Altair and Playground.

**Comment by agentd00nut** [comment]
Hey really sorry to keep reopening this but even with the graphQL playground the example still fails on subscriptions...

I have both index running and subscriptions running (if i don't then index complains about not being able to connect to its socket server, which makes sense of course)

Requesting the subscription from graphQL Playground gets me
```
{
  "error": "Could not connect to websocket endpoint ws://localhost. Please check if the endpoint url is correct."
}
```

and looks like 
```
[Wed Jun 24 11:00:53 2020] 127.0.0.1:57758 Accepted
[Wed Jun 24 11:00:53 2020] 127.0.0.1:57758 Invalid request (Malformed HTTP request)
[Wed Jun 24 11:00:53 2020] 127.0.0.1:57758 Closing
```
on the index.php

So even with graphQL Playground i'm unable to get subscriptions to properly connect and and idle waiting for something to be published.

**Comment by lemonbrain-mk** [comment]
is it maybe possible, that you are missing your endpoint port. i'm using it with apache proxy and it works also with playground https://github.com/lemonbrain-mk/graphql_websocket/wiki/3.-Apache

**Comment by leocavalcante** [comment]
@agentd00nut I just upgraded `webonyx/graphql-php` to v14, all automated and manual tests I used to do passed. Can you check if it is just missing the port like @lemonbrain-mk suggested?

I'm personally using Altair lately, specially because is the only that supports file uploads. Altair is also clearer about the subscriptions URL (is the third icon on the menu). Make sure you add the WS url with the proper port (3000 is the default).

Also, I've added a GraphQL config manifest with this setting, try reoping Playground pointing to the directory that has this file: https://github.com/siler-examples/issue-281/blob/master/.graphqlconfig

**Comment by agentd00nut** [comment]
Okay i finally got it using Altair.

1. It's not clear from the siler documentation that subscription requests need to be directed to the websocket server.   I guess i expected the http server to detect a socket request; see that it had a socket handler & subscriptions defined and redirect to the socket server magically.

2. Insomnia obviously failed to connect to the socket server; but Playground also seems to be bugged in some way which was a cause for further confusion... here's Altair properly getting messaging with playground failing to connect to the same address.
![image](https://user-images.githubusercontent.com/17181495/85880580-3cc3a700-b7aa-11ea-9235-bd8b939ab9c6.png)


Updating docs to explicitly explain that subscription requests should go to the socket server and to suggest using Altair over Playground might avoid people as dense as me from bothering you in the future :)

Thanks for your help and patience!

**Comment by leocavalcante** [comment]
Check again the websocket URL you provided for Playground. Look, it is missing a *L*, the screenshot says `locahost` instead of `localhost`.

I guess any other GraphQL's server or client will use different endpoints for queries+mutations vs. subscriptions, because they usually works with different transport layers (http vs. websocket), it is not a Siler thing, but I'll try to make it more clear on the docs for devs that are newcomers in GraphQL as a hole, thanks for the feedback.

**Comment by agentd00nut** [comment]
Ah you're right;
I got it here, it's still a bit janky through playground because i find i have to create a new workspace thats pointing at `http://localhost:3000` causing it to complain about not being to connect to the host (when it tries to find the schema) but doing a subscription query does work.  ie.

![image](https://user-images.githubusercontent.com/17181495/86025142-de8e0280-b9fb-11ea-8239-052d8df4a19a.png)

But yea thanks again!

**Comment by leocavalcante** [comment]
Actually you don't need to put the websocket address (`http://localhost:3000` nor `ws://localhost:3000`) in the Playground's address bar, you just point where there websocket server is using a `.graphqlconfig` file and you can make subscriptions operations to the regular HTTP endpoint (`http://localhost`).
